<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 * @var \Magento\Framework\Escaper $escaper
 */
$welcomeMessage = $block->getWelcome();
?>
<?php if ($block->getShowPart() == 'welcome') : ?>
  <div style="display: contents;"  data-bind="scope: 'customer'">
    <!-- ko if: customer().fullname -->
<li  
    class="greet welcome logged-in">
    <span class="logged-in"
          data-bind="text: new String('<?= $escaper->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
    </span>
</li>
<!-- /ko -->

<!-- ko ifnot: customer().fullname -->
<li style="margin-right: auto;"  
    class="greet welcome not-logged-in">
    <span class="not-logged-in"
          data-bind="html: '<?= $escaper->escapeHtmlAttr($welcomeMessage) ?>'">
    </span>
    <?= $block->getBlockHtml('header.additional') ?>
</li>
<!-- /ko -->
  </div>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
